version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: matheshwarsr/backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb
    depends_on:
      - mongo

  frontend:
    image: matheshwarsr/frontend:latest
    container_name: frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

volumes:
  mongo-data:
