version: '3'
services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: matheshwarsr/backend:latest
    container_name: backend
    ports:
      - "8082:8080"
    depends_on:
      - mongo

  frontend:
    image: matheshwarsr/frontend:latest
    container_name: frontend
    ports:
      - "8081:80"

volumes:
  mongo-data:
